### ISSUE TITLE
支付接口报签名错误

### ISSUE THREAD

**Issue by juckknife** [qbhy/tt-microapp#1]
你好，支付接口由于没有过滤 risk_info 导致客户端拉起支付报错

![image](https://user-images.githubusercontent.com/8176468/79300761-3ac3a900-7f1a-11ea-85a8-592e5076fb63.png)

**Comment by qbhy** [comment]
> 你好，支付接口由于没有过滤 risk_info 导致客户端拉起支付报错
> 
> ![image](https://user-images.githubusercontent.com/8176468/79300761-3ac3a900-7f1a-11ea-85a8-592e5076fb63.png)

你的图片我看不到了，方便加群讨论吗 ？QQ群：873213948

**Comment by qbhy** [comment]
https://github.com/qbhy/tt-microapp/releases/tag/2.3.0
